version: '3'
services:
  syslog-ng:
    restart: always
    container_name: syslog-ng
    image: balabit/syslog-ng:latest
    ports:
      - 514:514/udp
      - 601:601
    environment:
      - TZ=Asia/Shanghai